server:
  port: 3000

spring:
  ai:
    mcp:
      server:
        name: json-mcp-server
        protocol: STREAMABLE
        version: 0.0.1

logging:
  level:
    io:
      modelcontextprotocol:
        client: ${MCP_LOG_LEVEL:INFO}
        spec: ${MCP_LOG_LEVEL:INFO}
        server: ${MCP_LOG_LEVEL:INFO}
        mcp: ${MCP_LOG_LEVEL:INFO}

mcp:
  tools:
    file:
      allowed-extensions: .json
